### ISSUE TITLE
Ruby version that's installed isn't compatible with wpscan

### ISSUE THREAD

**Issue by wwwroth** [michaelck/vagrant-wpscan#1]
Great project! Being a PHP engineer I'm not too familiar with setting up a local Ruby env so this is helpful. I'm having some issues though I'm working on fixing. It seems the Ruby version that gets installed via Puppet isn't compatible with WPScan since there's some deprecated functions. I'm working on upgrading but now it's conflicting with other bundle deps. If I fix I'll submit a PR.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/wpscan$ ruby wpscan.rb
wpscan.rb:8:in `<main>': undefined local variable or method `__dir__' for main:Object (NameError)
```

**Comment by michaelck** [comment]
@wwwroth thanks for mentioning this. I feel like the ideal solution boils down to altering the config so that it install Ruby Version Manager (https://rvm.io/).

I'm happy to update or work with you to accept a PR
